name: Contributors
on:
  schedule:
    - cron: '0 1 * * 0' # At 01:00 on Sunday.
  push:
    branches:
      - dev
jobs:
  contributors:
    runs-on: ubuntu-latest
    steps:
      - uses: hyperledger-tooling/github-contributors-action@v0.0.1
        env:
          GITHUB_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CONTRIBUTORS_SECTION_PATTERN: "# # Contributors"
          CONTRIBUTORS_SECTION_END_PATTERN: "## License"
          FILE_WITH_PATTERN: ./README.md